// Generated by CoffeeScript 1.12.7
(function() {
  var Vec2;

  Vec2 = Crafty.math.Vector2D;

  Crafty.c("BackgroundObject", {
    backgroundObject: function(info) {
      this.requires("2D, Canvas, Image");
      this.image(info.path);
      this.base_pos = new Vec2(info.x, info.y);
      this.x = info.x;
      this.y = info.y;
      this.alpha = info.alpha;
      this.depth = info.depth;
      return Crafty.bind("ViewPortChanged", this.set_parallax.bind(this));
    },
    set_parallax: function() {
      var offset, vx, vy;
      vx = Crafty.viewport.x;
      vy = Crafty.viewport.y;
      offset = (new Vec2(-vx, -vy)).scale(this.depth).add(this.base_pos);
      this.x = offset.x;
      return this.y = offset.y;
    }
  });

}).call(this);
