// Generated by CoffeeScript 1.12.7
(function() {
  var Vec2, bullet_last_update;

  Vec2 = Crafty.math.Vector2D;

  bullet_last_update = 0;

  window.clear_bullet_canvas = function() {
    var c, ctx;
    c = $("#bullet_canvas")[0];
    if (c != null) {
      ctx = c.getContext("2d");
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, c.width, c.height);
      return ctx.setTransform(1, 0, 0, 1, Crafty.viewport.x, Crafty.viewport.y);
    }
  };

  Crafty.c("Bullet", {
    init: function() {
      this.requires("2D, Collision");
      this.width = 1;
      this.color_head = "rgba(255, 255, 255, 1)";
      this.color_tail = "rgba(255, 255, 255, 0)";
      this.armor_dmg = 1;
      this.shield_dmg = 1;
      this.duration = 1000;
      this.now = this.start_time = Date.now();
      this.animating = true;
      this.my_team = null;
      this.c = $("#bullet_canvas")[0];
      if (this.c == null) {
        this.c = document.createElement("canvas");
        this.c.id = "bullet_canvas";
        this.c.width = Crafty.viewport.width;
        this.c.height = Crafty.viewport.height;
        this.c.style.position = "absolute";
        this.c.style.left = "0px";
        this.c.style.top = "0px";
        Crafty.stage.elem.appendChild(this.c);
      }
      this.ctx = this.c.getContext("2d");
      this.bind("EnterFrame", this.on_frame);
      this.collision(new Crafty.polygon([0, 0]));
      return this.onHit("Damagable", this.on_hit);
    },
    bullet: function(my_team) {
      this.start_pos = new Vec2(this.x, this.y);
      return this.my_team = my_team;
    },
    stop: function() {
      if (this.animating) {
        this.animating = false;
        this.now = Date.now();
        return this.duration -= this.now - this.start_time;
      }
    },
    start: function() {
      if (!this.animating) {
        this.animating = true;
        return this.start_time = Date.now();
      }
    },
    on_frame: function(e) {
      var len, lingrad, trail_mid;
      if (bullet_last_update < e.frame) {
        bullet_last_update = e.frame;
        window.clear_bullet_canvas();
      }
      if (window.currentLevel.state === "planning") {
        this.stop();
      } else if (window.currentLevel.state === "animating") {
        this.start();
      }
      this.now = this.animating ? Date.now() : this.now;
      if (this.now - this.start_time < this.duration) {
        if (this.animating) {
          this.x += this.vx;
          this.y += this.vy;
        }
        len = this.start_pos.distance(new Vec2(this.x, this.y));
        if (len > 80) {
          this.start_pos.scale(80 / len).add(new Vec2(this.x, this.y).scale(1 - 80 / len));
        }
        trail_mid = Math.max(0, 1 - 15 / len);
        this.ctx.beginPath();
        lingrad = this.ctx.createLinearGradient(this.start_pos.x, this.start_pos.y, this.x, this.y);
        lingrad.addColorStop(0, this.color_tail);
        lingrad.addColorStop(trail_mid, this.color_head);
        lingrad.addColorStop(1, this.color_head);
        this.ctx.strokeStyle = lingrad;
        this.ctx.lineCap = "round";
        this.ctx.lineWidth = this.width;
        this.ctx.moveTo(this.start_pos.x, this.start_pos.y);
        this.ctx.lineTo(this.x, this.y);
        return this.ctx.stroke();
      } else if (this.animating) {
        return this.destroy();
      }
    },
    on_hit: function(e) {
      var i, len1, results, s;
      if (this.duration <= 0) {
        return;
      }
      results = [];
      for (i = 0, len1 = e.length; i < len1; i++) {
        s = e[i];
        if (s.obj.team !== this.my_team) {
          this.duration = 0;
          s.obj.take_dmg(this);
          results.push(this.unbind("Hit", this.on_hit));
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  });

}).call(this);
