// Generated by CoffeeScript 1.12.7
(function() {
  var buildButton, load_level, winner;

  winner = null;

  buildButton = function(label, pos, click_handler) {
    var entity;
    entity = Crafty.e("2D, Canvas, Mouse, Text").attr({
      x: 500,
      y: 250 + pos * 40,
      h: 20,
      w: 200
    });
    entity.text(label).textColor("#FFFFFF").textFont({
      family: "Helvetica",
      size: "20px"
    });
    return entity.bind("Click", click_handler);
  };

  load_level = function(lvl) {
    return Crafty.scene("level_" + lvl);
  };

  Crafty.scene("menu", function() {
    var i, j, name, ref, results;
    Crafty.viewport.x = 0;
    Crafty.viewport.y = 0;
    Crafty.background("url('assets/titlescreen.png')");
    Crafty.viewport.mouselook(false);
    if (winner) {
      Crafty.e("2D, Canvas, Text").attr({
        x: 400,
        y: 180,
        h: 30
      }).text(winner.name + " has won").textColor("#FFFFFF").textFont({
        family: "Helvetica",
        size: "30px"
      });
    }
    results = [];
    for (i = j = 1, ref = window.levels.length - 1; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      name = window.levels[i] ? ": " + window.levels[i].name : "";
      results.push(buildButton("Level " + i + name, i - 1, load_level.bind(null, i)));
    }
    return results;
  });

}).call(this);
